### ISSUE TITLE
greenlight error 404 not found 

### ISSUE THREAD

**Issue by essamcis** [strongpapazola/greenlight_installer#1]
i did all steps for installation and everything goes correct but still its not running 
any advice ??

root@learn:~/greenlight# sudo systemctl restart nginx
root@learn:~/greenlight# cd ~/greenlight
root@learn:~/greenlight# docker-compose down
Stopping greenlight-v2   ... done
Stopping greenlight_db_1 ... done
Removing greenlight-v2   ... done
Removing greenlight_db_1 ... done
Removing network greenlight_default
root@learn:~/greenlight# ./scripts/image_build.sh {name_image} {release_name}
-bash: ./scripts/image_build.sh: No such file or directory
root@learn:~/greenlight# docker-compose up -d
Creating network "greenlight_default" with the default driver
Creating greenlight_db_1 ... done
Creating greenlight-v2   ... done

**Comment by strongpapazola** [comment]
You can wait a few minutes after installation ...
kamu bisa menunggu beberapa menit setelah installasi...
